### ISSUE TITLE
taxnomoy in separate table?

### ISSUE THREAD

**Issue by tmihetec** [Lecturize/Laravel-Taxonomies#1]
Hi, shouldn't it be better if taxnomies have separate table? with id and name?

**Comment by AlexanderPoellmann** [comment]
In most cases you will use only a limited number of maybe 5 to 10 taxonomies, that's why I didn't go for a seperate table and put the taxonomy right into the 'taxonomies' table relating it like so to the term id.

But even if you have more taxonomies I don't really see the need or benefit for a separate table here.
