### ISSUE TITLE
Messing with Terms and Taxonomies

### ISSUE THREAD

**Issue by IsraelOrtuno** [Lecturize/Laravel-Taxonomies#14]
Correct me if I am wrong but I think the database structure is wrong since Taxonomies are belonging to Terms and I believe it should be the other way around:

https://developer.wordpress.org/themes/basics/categories-tags-custom-taxonomies/#default-taxonomies

This caused me a lot of confusion when inspecting the code until I was able to understand. In WP it may look confusing too since there's not a Taxonomies table, `wp_terms_taxonomy` has a `taxonomy` string field which acts as such, but it doesn't mean that a term HasMany taxonomies.

From WP definition:

> Terms are items within your taxonomy. So, for example, if you have the Animal taxonomy you would have the terms, dogs, cats, and sheep.

**Comment by AlexanderPoellmann** [comment]
WP Taxonomies is quite a complicated thing, so let me explain right away what I needed to accomplish:

Imagine you have a page with a blog and a shop, that makes two taxonomies: `taxonomy_blog` and `taxonomy_shop`

You're selling shoes and shirts, so you would have two terms ("categories"): `Shoes` and `Shirts`.

Now you sell them **and** blog about them, so in your `taxonomies` table you'll see:

| ID | taxonomy            | term_id |
| -- | ------------------- | --------- |
| 1  | `taxonomy_blog` | 1 |
| 2  | `taxonomy_blog` | 2 |
| 3  | `taxonomy_shop` | 1 |
| 4  | `taxonomy_shop` | 2 |

And your `terms` table:

| ID | title      |
| -- | -------- |
| 1  | `Shoes` |
| 2  | `Shirts` |

So, if for some reason you want to rename the term `Shoes` to `Super Shoes` you would have to rename only one term instead two (or `n` terms) in order to keep wording consistent throughout your site.

Still you may add two terms `Shoes` (attention cause slugs will be unique!) and assign them to different taxonomies if you want to, but then one simply could've added a `title` column to the `taxonomies` table and use this as a simple categories package. With this package on the other hand you can manage more than just categories but also taxonomies similar (not exactly like) to the WordPress taxonomies system. Think of post types, ...

I hope this explanation helps / answers your question, otherwise let me know!

**Comment by IsraelOrtuno** [comment]
I have developed a very similar package in the past few days trying to achieve the same thing. It isn't on packagist yet but here is the source code:

https://github.com/IsraelOrtuno/laravel-taxonomy

It's heavily inspired on [`spatie/laravel-tags`](https://github.com/spatie/laravel-tags) but since I needed more information about Taxonomies, I decided to make my own where Taxonomies have their own table and can be extended as needed.

Here we would have this:

** taxonomies **
| ID | name
| --| --
| 1 | Category
| 2 | Size

** terms **
| ID | name | taxonomy_id
| --| --|--
| 1 | Shirts | 1
| 2 | Shoes | 1
| 3 | XS | 2
| 4 | M | 2
| 5 | L | 2

If you need to change the taxonomy name, you can do it in a single place. If you need to change a term name, you can do in a single place. 

For me, a taxonomy would be like a "type" of terms. Not sure if I am not understanding the Taxonomy/Term paradigm.

**Comment by AlexanderPoellmann** [comment]
Okay, so what you need is what I would call "attributes", not taxonomies. A taxonomy is some sort of a classification (Shirts, Shoes, ...), while an attribute describes a certain feature of said product (size, color, ...)

I can't access your package as it seems to be private.

Anyways, for example `size` is an attribute of a product, while `Shirts` would be a taxonomy/category grouping similar items.

So, if you ask me, in your example you are mixing two different things. Tags would again be a completely different thing.
